### ISSUE TITLE
Audit Button

### ISSUE THREAD

**Issue by edzee** [Pearson-Higher-Ed/o-buttons#1]
# Colors 

#### Primary 
- ![](http://placehold.it/20x10/107ACA/107ACA) `#107ACA` Blue (Background)
- ![](http://placehold.it/20x10/0e6ab0/0e6ab0) `#0E6AB0` Blue (Border)
- ![](http://placehold.it/20x10/FFFFFF/FFFFFF) `#FFFFFF` White (Text)

#### Default
- ![](http://placehold.it/20x10/F8F8F8/F8F8F8) `#F8F8F8` Light Gray (Background)
- ![](http://placehold.it/20x10/D0D0D0/D0D0D0) `#D0D0D0` Gray (Border)
- ![](http://placehold.it/20x10/666666/666666) `#666666` Gray (Text)

#### Primary
- ![](http://placehold.it/20x10/0C5D99/0C5D99) `#0C5D99` Blue (Background)
- ![](http://placehold.it/20x10/0A4D80/0A4D80) `#0A4D80` Blue (Border)
- ![](http://placehold.it/20x10/FFFFFF/FFFFFF) `#FFFFFF` White (Text)

#### Default
- ![](http://placehold.it/20x10/CCCCCC/CCCCCC) `#CCCCCC` Gray (Background)
- ![](http://placehold.it/20x10/BBBBBB/BBBBBB) `#BBBBBB` Gray (Border)
- ![](http://placehold.it/20x10/4D4D4D/4D4D4D) `#4D4D4D` Gray (Text)

#### Primary 
- ![](http://placehold.it/20x10/9DC0DB/9DC0DB) `#9DC0DB` Light Blue (Background)
- No Border
- ![](http://placehold.it/20x10/FFFFFF/FFFFFF) `#FFFFFF` White (Text)

#### Default
- ![](http://placehold.it/20x10/CCCCCC/CCCCCC) `#CCCCCC` Gray (Background)
- No Border
- ![](http://placehold.it/20x10/888888/888888) `#888888` Gray (Text)

# Sizes
Border radius on all buttons: 3px
### Large
- Font size: 18px
- Line height: 42px
- Padding: 0 20px

### Default
- Font size: 14px
- Line height: 28px
- Padding: 0 12px

### Small
- Font size: 13px
- Line height: 24px
- Padding: 0 10px

**Comment by aarmour** [comment]
```
o-buttons
o-buttons--primary
o-buttons--small
o-buttons--large
o-buttons--disabled
```
